{% set name = "pyradios" %}
{% set version = "2.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyradios-{{ version }}.tar.gz
  sha256: 15101dd4cf09648b2880b6bf5bbf0841d74cc46d19f2d00ff88895b4753d7e9e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - httpx >=0.25.2

test:
  imports:
    - pyradios
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/andreztz/pyradios
  summary: A Python wrapper for the http://www.radio-browser.info/webservice
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
