{% set name = "pyradios" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyradios-{{ version }}.tar.gz
  sha256: e03a55b1c5ad1695b0d54516c9b85972c273fbbf4c6cf64235f77c8d56427566

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - appdirs >=1.4.3
    - python  >=3.6
    - requests >=2.22.0

test:
  imports:
    - pyradios
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/andreztz/pyradios
  summary: A Python wrapper for the http://www.radio-browser.info/webservice
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
