{% set name = "pyradios" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyradios-{{ version }}.tar.gz
  sha256: 5d3a70f1b805668df93c99e0afda30794e9f637280a6126cac48642b35872c80

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - httpx >=0.25.2

test:
  imports:
    - pyradios
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/andreztz/pyradios
  summary: A Python wrapper for the http://www.radio-browser.info/webservice
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
